### ISSUE TITLE
The environment variable for the data directory of Ivory SQL in the Dockerfile does not match the mounted data directory.

### ISSUE THREAD

**Issue by highgo-srk** [IvorySQL/docker_library#4]
In the Dockerfile-redhat.template file, the environment variable PGDATA is set to /var/local/ivorysql/ivorysql-$IVORY_MAJOR/data, but the mounted volume path below is /var/lib/ivorysql/data. The environment variable and the mounted volume path do not match.

ENV PGDATA /var/local/ivorysql/ivorysql-$IVORY_MAJOR/data
....
VOLUME /var/lib/ivorysql/data

**Comment by balinorLiang** [comment]
issue has been fixed #6
